[package]
name = "frost-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
frost-dalek = "0.2.3"
clap = { version = "4.4", features = ["derive"] }
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rand = "0.7"